<?php
if(!$this->getEnabled()) return;
$selector = 'alo-content-'.uniqid();
$franchises = $this->getFranchises();
if(!count($franchises)) return;
?>
<div class="<?php /* @escapeNotVerified */ echo $selector ?>" data-mage-init='{"gridSlider": {}}'>
    <?php /* @escapeNotVerified */ echo $this->getTitle() ? '<h2 class="title item">' . '<span>' . $this->getTitle() . '</span>' . '</h2>' : '' ?>
    <div class="shopfranchise grid-slider"
    <?php foreach ($this->getFrontendCfg() as $opt) :?>
        data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getData($opt) ?>'
    <?php endforeach;?>  
    >
        <?php $i=0; foreach ($franchises as $franchise) :?>
            <div class="item">
                <a href="<?php /* @escapeNotVerified */ echo $this->getUrlFranchise($franchise) ?>">
                    <img class="franchise img-responsive" src="<?php /* @escapeNotVerified */ echo $this->getImage($franchise)?>" alt="<?php /* @escapeNotVerified */ echo __($franchise->getTitle()) ?>" title="<?php /* @escapeNotVerified */ echo __($franchise->getTitle()) ?>" />
                </a>
            </div>
        <?php endforeach ?>
    </div>
</div>
