<?php
/**
 * Magiccart 
 * @category     Magiccart 
 * @copyright     Copyright (c) 2014 Magiccart (http://www.magiccart.net/) 
 * @license     http://www.magiccart.net/license-agreement.html
 * @Author: DOng NGuyen<nguyen@dvn.com>
 * @@Create Date: 2016-05-08 22:57:12
 * @@Modify Date: 2018-03-15 00:53:41
 * @@Function:
 */
 ?>
<?php 
if(!$this->getEnabled()) return;
$selector = 'alo-content-'.uniqid();
$franchises = $this->getFranchises();
$numTabs = count($franchises);
if(!$numTabs) return;
?>
<div class= "<?php /* @escapeNotVerified */ echo $selector?> magicproduct autoplay">
    <?php /* @escapeNotVerified */ echo $this->getTitle() ? '<h3 class="title">' . '<span>' .$this->getTitle(). '</span>' . '</h3>' : '' ?>
    <div class="shopfranchise-box">
        <div class="magictabs" data-ajax ='<?php echo $this->getAjaxCfg() ?>'>
            <div class="shopfranchise grid-slider"
            <?php foreach ($this->getFrontendCfg() as $opt) :?>
                data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getData($opt) ?>'
            <?php endforeach;?>  
            >
            <?php $activated = 'activated'; //$this->getTabActivated();
                $single = ($numTabs ==1) ? 'single' : '';
                foreach ($franchises as $franchise):
                    $type = $franchise->getData('option_id'); //$franchise->getShopfranchiseId();
                    if($activated){
                        $status = "activated loaded $single";
                        $activated = '';
                    } else $status = '';
                    /* @escapeNotVerified */ echo '<div class="item '.$status.'" data-type ="'.$type.'"><img class="franchise img-responsive" src="' . $this->getImage($franchise) .'" alt="' . __($franchise->getTitle()) . '" title="' .__($franchise->getTitle()) .'" /></div>';
                endforeach;
            ?>
            </div>
        </div>
        <div class="ajax_loading" style="display:none" data-url="<?php /* @escapeNotVerified */ echo $this->getUrl('shopfranchise/index/product', array('_secure'=>$this->getRequest()->isSecure()))?>"></div>
        <div class="content-products" 
        <?php foreach ($this->getFrontendProductCfg() as $opt) :?>
            data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getProductCfg($opt) ?>'
        <?php endforeach;?>        
        >
        <?php echo $this->getContent('product/grid.phtml'); ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    require(['jquery','gridSlider'], function($, gridSlider){
        var el  = $('.<?php echo $selector ?>');
        if(el.length) el.gridSlider();
    });
    require(['magicproduct']);
</script>
