<?php
$franchise = $block->getFranchise();
if(!$franchise) return;
$helper =  $this->_helper;
$image = $franchise->getImage();
$description = $this->getDescription();
?>
<h1 class="title"><?php echo $franchise->getTitle(); ?></h1>
<?php if($image) : ?>
<div class="franchise-view">
    <div class="image">
        <img class="img-responsive" src="<?= $helper->getMediaUrl($image) ?>" alt="<?= $franchise->getTitle(); ?>"/>
    </div>
    <?php endif; ?>
    <?php echo $description ? '<div class="franchise-description">' . $description . '</div>' : ''; ?>
</div>
