<?php
    $franchise = $this->getFranchise();
    if(!$franchise) return;
?>
<div class="franchise">
    <h3 class="title"><?php echo __('Franchise') ?></h3>
    <a href="<?php echo $this->getUrlFranchise($franchise) ?>">
        <span><?php echo __($franchise->getLabel()) ?></span>
        <?php if($franchise->getData('image')) : ?>
        <img class="franchise img-responsive" src="<?php /* @escapeNotVerified */ echo $this->getImage($franchise)?>" alt="<?php /* @escapeNotVerified */ echo __($franchise->getTitle()) ?>" title="<?php /* @escapeNotVerified */ echo __($franchise->getTitle()) ?>" />
        <?php endif ?>
    </a>
</div>
