<?php
/**
 *
 * @var $block \Magiccart\Shopfranchise\Block\ListFranchise
 * 
 */
?>
<?php
$selector = 'alo-content-'.uniqid();
$helper = $this->_helper;
$productCount = $helper->getConfigModule('list_page_settings/show_product_count');
$franchises = $block->getFranchises();
$keyword = $this->getRequest()->getParam('keyword');
?>
<?php echo $block->getChildHtml('franchise_filter_by_character'); ?>
<div class="shop-by-franchise <?php /* @escapeNotVerified */ echo $selector ?>" >
    <div class="block block-search franchise-search">
        <form class="form minisearch form-search franchise-form-search" id="shopfranchise_search_mini_form" action="<?php echo $helper->getUrlRouter() ?>" method="get">
            <div class="field search">
                <label class="label franchise-label" for="franchise-search">
                    <span><?php echo __('Search franchise') ?></span>
                </label>
                <div class="control-search">
                    <input class ="keyword" type="text" name="keyword" placeholder="<?php echo __('Search a franchise') ?>" value="<?php echo $block->escapeHtml($keyword) ?>"/>
                </div>
                <div class="actions">
                    <button type="submit" title="<?php echo __('Search') ?>" class="action search">
                        <span><?php echo __('Search') ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
<?php if(!$franchises->count()) : ?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find franchises matching the selection')) ?></div></div>
<?php return;?>
<?php endif;?>
    <div class="shopfranchise">
        <div class="franchise-list grid-slider"
            <?php foreach ($this->getFrontendCfg() as $opt) :?>
                data-<?php /* @escapeNotVerified */ echo $opt ?>='<?php /* @escapeNotVerified */ echo $this->getData($opt) ?>'
            <?php endforeach;?>  
        >
        <?php foreach ($franchises as $franchise) : ?>
            <?php $href = $helper->getLinkFranchise($franchise); ?>
            <div class="item">
                <div class="image">
                    <a href="<?= /* @escapeNotVerified */ $href ?>">
                        <img class="img-responsive" src="<?= /* @escapeNotVerified */ $helper->getMediaUrl($franchise->getImage()) ?>" alt="<?= /* @escapeNotVerified */ $franchise->getName(); ?>"/>
                    </a>
                </div>
                <div class="name">
                    <a class="link-franchise" href="<?= /* @escapeNotVerified */ $href ?>">
                        <?= $franchise->getTitle(); ?>
                        <?php if ($productCount): ?>
                            <span>(<?= $block->getProductCount($franchise) ?>)</span>
                        <?php endif ?>
                    </a>
                </div>
            </div>
        <?php endforeach; ?>
        </div> 
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'gridSlider',
        ], function($, gridSlider){
            var el  = $('.<?php echo $selector ?>');
            if(el.length) el.gridSlider();
    });
</script>